apiVersion: v1
kind: Service
metadata:
    name : my-nginx

spec:
    ports:
        - name : http
          port : 8080
          targetPort: 80
          nodePort: 31080
    selector:
        app: my-nginx
    type: NodePort
